Updates dcrwallet-tickets.md with steps for v1.6
decred/dcrdocs pull request #1148
Opened 2021-01-31 03:53 UTC by dezryth

I have written changes to the dcrwallet-tickets.md page to add steps for staking with a VPS via vpsd as of v1.6.0, as well as added verbiage to differentiate steps that refer to the legacy method of purchasing tickets and delegating voting rights to a VSP.

2021-02-03 10:57 UTC, jholdstock requested changes
Looks great, just a few minor things to look at.

There is a section under the "Decisions" heading which mentions delegation via multi-sig, that needs updating/removing. The mention of "smaller absolute fees" can also be removed.

2021-02-03 10:57 UTC, jholdstock commented on docs/wallets/cli/dcrwallet-tickets.md
> + You can find a list of VSP [here](../../proof-of-stake/how-to-stake.md#pos-using-a-voting-service-provider-vsp).
VSPs*

2021-02-03 10:57 UTC, jholdstock commented on docs/wallets/cli/dcrwallet-tickets.md
> +To get the current ticket price, issue the `dcrctl --wallet getstakeinfo` command and look for the `difficulty` value. This is the price of each ticket in the current price window. you will want to a
You*

2021-02-03 10:57 UTC, jholdstock commented on docs/wallets/cli/dcrwallet-tickets.md
> +You also need to specify options within your config file for your VSP as outlined [here.](#vsp-voting)
Need an empty newline before this

2021-02-03 10:57 UTC, jholdstock commented on docs/wallets/cli/dcrwallet-tickets.md
> +Note: The info below is now considered "legacy" and will be phased out at a later date. It is recommended to use the process [here](#vsp-voting) to purchase tickets with a VSP as of version 1.6.0 and
Need an empty newline before this.

Without it, this text is formatted weirdly

2021-02-03 19:57 UTC, dezryth commented
Thanks very much for the code review! I will push the requested changes shortly.

2021-02-10 09:27 UTC, jholdstock approved these changes

2021-02-10 09:28 UTC, merged