Using the Block Explorer: Update & Reorganize
decred/dcrdocs pull request #1195
Opened 2022-05-24 05:51 UTC by matthawkins90

Based on [this reddit thread](https://www.reddit.com/r/decred/comments/uqrdpa/comment/i8su4lb/) from Dave, and noticing that it caused confusion while PhoenixGreen was making an informational video, I decided to update the docs to be more accurate.

The first commit is just to correct the problems that Dave mentioned.

The second commit is to tidy things up a bit, and to reorganize the structure so that it more closely matches the [dcrdata api](https://dcrdata.decred.org/api/block/661673/verbose?indent=true). This organization is a bit subjective, but I felt like the previous structure didn't have any rhyme or reason, so why not just try to follow dcrdata.

2022-05-31 08:37 UTC, jholdstock requested changes
A few minor suggestions but overall great stuff

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +        - Tickets which will enter the stakepool
"stakepool" not really the correct term here, "ticket pool" would be more accurate.

tbh I'd just go with "Proof-of-Stake ticket purchases".

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +        - Proof-of-Stake Votes and Rewards
```suggestion
        - Proof-of-Stake votes and rewards
```

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +        - The Proof-of-Work Reward
```suggestion
        - The Proof-of-Work reward
```

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +        - The Treasury Reward
```suggestion
        - The Treasury reward
```

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +Parameter                | Explanation
"Option" was definitely the wrong word here, but I don't particularly like "Parameter" either. To a developer it implies an argument passed into a function (which isn't accurate), and non-developers might not know the word at all. 

How about "Value" instead?

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +`Size`                   | The size of the block (in bytes).
dcrdata is currently showing kB, not B. Maybe it was bytes at the time this was originally written, idk.

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +`Number of Transactions` | The number of standard transactions (DCR sent from one user to another).
Please update this to "regular" as commented above. "Standard" has a slightly different meaning.

To give you some reference for these terms, [standard](https://github.com/decred/dcrd/blob/master/txscript/stdscript/README.md) and [regular](https://docs.decred.org/glossary/#regular-transaction-tree)

2022-05-31 08:37 UTC, jholdstock commented on docs/getting-started/using-the-block-explorer.md
> +For a more advanced description of block headers, see the Dev Docs on [Block Header Specifications](https://devdocs.decred.org/developer-guides/block-header-specifications/).
I think this line would be better above the table. Its easy to miss at the bottom.

2022-07-17 22:23 UTC, matthawkins90 commented
Sorry it took so long!

2022-07-18 07:59 UTC, jholdstock approved these changes

2022-07-18 07:59 UTC, merged